sudo: required
services:
  - docker

before_install:
  - docker build -t mrjai20/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrjai20/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-836929800576"
  bucket_path: "Docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  